# Generated by Django 5.1.2 on 2024-11-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='condicion_precio',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
